% script for detecting and storing all movement artifact time intervals
% into an NWB file, to be accessed thru the MASTER file of the same name
% using external link. 

%% 

clear; clc;

%%

% CONFIGURATION & CONSTANTS
% decide whether to show all figures generated by workflow
cfg.displayWorkflowFigs = false;

% (the the rest of the constants See inside "tremorWorkflow" function at bottom of script)

cfg.fcDetrend = 1; % Hz

% Spectrogram parameters:
cfg.TWIN = 1; % seconds, sliding time-window of spectrogram
cfg.NOVERLAP = 0; % samples, no overlaps for these spectrogam windows

% Movement artifact removal
cfg.MADthresh = 3; % median limit for outliers

% Tremor frequency band
% trPeak = 10; % Hz, major tremor component
% trRange = 3; % limits of tremor band around major component
% cfg.tremorBand = [6, 12]; % Hz

% General movement frequency band
generalBand = [17, 21];

% Tremor power summary statistic & bootstrapped estimation of confidence interval
% myStatFun = @(x)mean(x);
cfg.NBOOTS = 1000;

% If any time-series recordings MUCH larger than the typical small size,
% break into smaller segments for display
cfg.tooBigTime = 240; % seconds
cfg.subSegTime = 90; % seconds
cfg.tooSmallTime = 30; % seconds

cfg.tooSparseData = 30;

% Baseline estimate statistic

% Test for segments vs baseline
statTest = @(x)signrank(x);

% False Discovery Rate for Benjamini-Hochberg procedure for multiple
% comparisons
fdr = 0.005;

errbCapSize = 0;
errbLineWidth = 1;
errbC = 'k';

scatSz = 30;
scatC = 'k'; 
scatCsig = 'r';

harLineWidth = 1.5;

pchipLineStyle = '--';
linC_M = 'b';
linC_K = 'm';
linC_U = 'g';



% MANUAL INPUTS:

% Fullpath for directory in which to save NWB file results
% nwbSavePn = [dataAcqPn 'NWBdata\KiwiPilot\'];
nwbSuffix = '_moveArt';
nwbDataPath = 'D:\PROJECTS\Thalamic DBS for Harmaline Tremors\Data Acquisition\NWBdata\';

projRootPath = 'L:\My Drive\PROJECTS\Thalamic DBS for Harmaline Tremors\';


% % Mela Pilot data of choice: 12 mg/kg day
% nwbFullPath = [nwbDataPath 'MelaPilot\'];
% % SESSION_ID = 'harPilotMela-150928-094900'; % 2 mg/kg day
% % SESSION_ID = 'harPilotMela-150930-082000'; % 6 mg/kg day
% SESSION_ID = 'harPilotMela-151013-072100'; % 12 mg/kg day


% % Kiwi Pilot data of choice: 10 mg/kg day
% nwbFullPath = [nwbDataPath 'KiwiPilot\'];
% SESSION_ID = 'harPilotKiwi-160517-122121';


% Uva Pilot data of choice: 8 mg/kg day
nwbFullPath = [nwbDataPath 'UvaPilot\'];
% SESSION_ID = 'harPilotUva-180219-132618'; % 8 mg/kg day
SESSION_ID = 'harPilotUva-180221-113120'; % 12 mg/kg day
% SESSION_ID = 'harPilotUva-180305-103016'; % 12 mg/kg day



%% Go thru whole  pipeline till I get movement artifact windows

% Load nwb master file for this session, get acc TimeSeries object
disp('Reading NWB file...')
nwbM = nwbRead([nwbFullPath SESSION_ID '_MASTER.nwb']);
disp('DONE!')


% Divide the NWB accelerometry data into data segments based on "ctrl" indices
accTseriesObj = nwbM.processing.get('ACCproc').deref().nwbdatainterface.get('ACCproc');
dims = accTseriesObj.data.dims;
acc = accTseriesObj.data.load([1, 1], [dims(1), 3]);
tst = accTseriesObj.timestamps.load;
ctrl = accTseriesObj.control.load;
fs = accTseriesObj.starting_time_rate;
tooBigSamp = floor(fs * cfg.tooBigTime);
subSamp = floor(fs * cfg.subSegTime);
[accSeg, tstSeg] = nwbnrtl.util.segmentTseriesByCtrl(acc, tst, ctrl, ...
    tooBigSamp, subSamp);
[accSeg, tstSeg, isTooShort] = remSegsTooShort(accSeg, tstSeg, cfg.tooSmallTime);


% Get cobmined triaxial spectrogram spectral data organized by data-segment 
[SaccCell, tEdgesCell, fSegs] = getSpecWindowsBySegment(accSeg, tstSeg, fs, cfg);


% Track which windows in all these segments contain movement artifacts
[~,~,artIdxSeg] = removeMovArtInAll(SaccCell, cfg);

artIdxAll = cell2mat(artIdxSeg);
tEdgesAll = cell2mat(tEdgesCell')';

% MAIN DATA RESULT OF INTEREST:
tEdgesArts = tEdgesAll(artIdxAll,:);



%% save within appropriate NWB field

% give file a globally unique id, more for machine readability than human
id = genUUID;


% Init NWB
nwb = NwbFile(...
    'session_start_time', nwbM.session_start_time, ...
    'identifier', id, ...
    'session_description', '<missing>', ...
    'timestamps_reference_time', nwbM.session_start_time);


% movement artifact intervals: convert my data into format that NWB expects
nIntervals = length(tEdgesArts);
intervals = [ones(nIntervals, 1), -1*ones(nIntervals, 1)];
data = reshape(intervals', [nIntervals*2, 1]);
timestamps = reshape(tEdgesArts', [nIntervals*2, 1]);

% data = 1:length(targOnset);
movementArtifactIntervals = types.core.IntervalSeries( ...
    'comments', 'times that movement artifacts detected. 1 is onset, -1 is offest. intervals is ALWAYS a [1 -1] pair, according to NWB guidelines.', ...
    'data', data, ...
    'data_unit', 'reach-count', ...
    'data_resolution', -1.0, ... % default for unknown
    'description', 'TargetOnset, ReachOnset, ReachEnd', ...
    'timestamps', timestamps);
    

BehavioralEpochs = types.core.BehavioralEpochs;
BehavioralEpochs.intervalseries.set('movementArtifactIntervals', movementArtifactIntervals);

nwb.acquisition.set('movementArtifacts', BehavioralEpochs);


%% Write the nwb file in one go

tic


fullSavePath = [nwbFullPath SESSION_ID nwbSuffix '.nwb'];

% Next two lines essentially let you overwrite an existing version of this
% nwb file
nwbnrtl.io.checkdelete(fullSavePath); 
nwbExport(nwb, fullSavePath)


disp('DONE EXPORTING NWB!');
toc




%% SUB-FUNCTIONS

function nwb = nwbfill_general(nwb)

nwb.general_data_collection = {'test'};
nwb.general_experiment_description = {'test'};
nwb.general_experimenter = {'Bello', 'Blumenfeld'};
% nwb.general_extracellular_ephys = 'test' % need to fix
% nwb.general_extracellular_ephys_electrodes = 'test' % need to fix 
nwb.general_institution = {'University of Minnesota'};
nwb.general_keywords = {'harmaline', 'touchscreen', 'lfp'};
nwb.general_lab = {'NRTL'};
nwb.general_notes = {'missing'};
nwb.general_pharmacology = {'missing'};
nwb.general_protocol = {'missing'};
nwb.general_subject = types.core.Subject(...
    'date_of_birth', '2001-01-01 00:00:00', 'description', 'nickname: Uva, source: breeder', ...
    'sex', 'F', 'species', 'macacca mulatta', 'subject_id', '13LP1');

nwb.general_devices.set('PZ5', types.core.Device());

end

function nwb = nwbfill_electrode(nwb)

deviceName = '2017_Numed-002';
nwb.general_devices.set(deviceName, types.core.Device());

% specify subgrouping of electrodes in recording device (here there's just
% one group, that is, all the DBS electrodes)
elecGroupName = 'DBSelectrodes';
nwb.general_extracellular_ephys.set(elecGroupName, ...
    types.core.ElectrodeGroup(...
    'description', 'linear array of annular electrodes', ...
    'location', 'lateral thalamus', ...
    'device', types.untyped.SoftLink(['/general/devices/', deviceName])));


% % set up electrode information table
% group_object_view = types.untyped.ObjectView( ...
%     ['/general/extracellular_ephys/' elecGroupName]);

% tableKeys = {'label', 'impedance', 'electrodeGroup'};
tableKeys = {'label', 'impedance'};
labels = {'C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'}'; 
% nElecs = numel(labels);
% id = [1:nElecs]';
imp = NaN(8,1);
tab = table(labels, imp);
% tab = table(labels(1), {NaN}, group_object_view);
% tab = table(1, labels(1), {NaN});
% 
% for iE = 2:nElecs
% %     tab = [tab; table(labels(iE), {NaN}, group_object_view)];
%         tab = [tab; table(iE, labels(iE), {NaN})];
% 
% end
% tab.Properties.DimensionNames = {'electrode', 'property'};
tab.Properties.VariableNames = tableKeys;
% tab.Properties.VariableDescriptions = {'naming convenction', 'abs imp @ 1kHz'};
tab.Properties.Description = 'information for use within nwb file';

elecDynTable = util.table2nwb(tab);
nwb.general_extracellular_ephys_electrodes = elecDynTable;

end

function id = genUUID
temp = java.util.UUID.randomUUID;
myuuid = temp.toString;
id = char(myuuid);
% fprintf('%s\n', char(myuuid))

end

function [SaccCell, tEdgesCell, fSegs] = getSpecWindowsBySegment(accSeg, tstSeg, fs, cfg)
% Arranges all resultant spectrogram data by data segment. 

nSegs = length(accSeg);


% Obtain summed triaxial spectrogram over time
for iSeg = 1:nSegs
    % get 1-second windows spectrogram of spectral info from each segment
    % of data
    [SaccCell{iSeg,1}, fSegs{iSeg,1}, tSpec] = spectrogramacc3(accSeg{iSeg,1}, fs, cfg);
    
    % get time-edges of each spectrogram PSD, time synced to beginning of
    % recording
    tSpecSync = tSpec + tstSeg{iSeg}(1);
    dt = median(diff(tSpecSync));
    tEdges = [tSpecSync(1) - (dt/2), tSpecSync + (dt/2)];
    tEdgesCell{iSeg,1} = [tEdges(1:end-1); tEdges(2:end)];
    
       
end



end

function [accSeg, tstSeg, isRemove] = remSegsSparseData(accSeg, tstSeg, tooSparseData)
% Mark the segments that have too little data points left after removing
% movement artifact data. then remove them from the cell array

nSegs = length(tstSeg);
isRemove = false(nSegs,1);
for iSeg = 1:nSegs
    acc = accSeg{iSeg};
    if size(acc, 2) < tooSparseData
        isRemove(iSeg) = true;
        
    end
    
end

accSeg(isRemove) = [];
tstSeg(isRemove) = [];


end

function [accSeg, tstSeg, isRemove] = remSegsTooShort(accSeg, tstSeg, tooSmallTime)
% Mark the segments that are too short in time width, then remove them from
% the cell array

nSegs = length(tstSeg);
isRemove = false(nSegs,1);
for iSeg = 1:nSegs
    tst = tstSeg{iSeg};
    if (tst(end) - tst(1)) <= tooSmallTime
        isRemove(iSeg) = true;
        
    end
    
end

accSeg(isRemove) = [];
tstSeg(isRemove) = [];



end

function [accSegFinal, tstSegFinal] = segmentacc(acc, tst, ctrl, maxSamp)
% separate acc data and timestamps into time segments based on recordings.
% Large recordings are further subdivided into smaller time segements according
% to max segment time. maxTime (seconds). ctrl has zero at the start of
% every recording. 

% for acc and tst composed of N separate recordings, ctrl tracks which data
% belongs to which N recording

% detect the number of segments
nSegs = max(ctrl);
for iSeg = 1:nSegs
    accSeg{iSeg,1} = acc((ctrl == iSeg),1:3);
    tstSeg{iSeg,1} = tst((ctrl == iSeg));
    nSamps(iSeg) = sum(ctrl == iSeg);
    
end

% If any segments are too long according to maxSamp 
accSegFinal = {};
tstSegFinal = {};
if exist('maxSamp', 'var')
    for iSeg = 1:nSegs
        if nSamps(iSeg) > maxSamp % Too big! subdivide the segment into smaller ones
            nSubs = floor(nSamps(iSeg)/maxSamp) + 1;
            tempAcc = accSeg{iSeg,1};
            tempTst = tstSeg{iSeg,1};
            
            % mark subdivisions with indices
            xb = 1:(nSubs-1);
            bIdx = [1, xb*maxSamp + 1];
            eIdx = [xb*maxSamp, nSamps(iSeg)];
            
            % loop-fill the new subsections to be added
            for iSub = 1:nSubs
                accSegFinal = [accSegFinal; {tempAcc(bIdx(iSub):eIdx(iSub),1:3)}];
                tstSegFinal = [tstSegFinal; {tempTst(bIdx(iSub):eIdx(iSub))}];
                
            end
            
%             xb = [1:nRowsAdd]';
% 
%             % begIdxCorr
%             begIdxSmall = begIdx(i) + xb*maxSamp + 1;
%             begIdxCorr = [begIdxCorr; begIdx(i); begIdxSmall];
% 
%             % endIdxCorr
%             endIdxSmall = begIdx(i) + xb*maxSamp;
%             endIdxCorr = [endIdxCorr; endIdxSmall; endIdx(i)];

        else
            accSegFinal = [accSegFinal; accSeg(iSeg,1)];
            tstSegFinal = [tstSegFinal; tstSeg(iSeg,1)];
        
        end
    
        
        
    end
    
else % simple case where maxSamp is not entered into the function, no subdivision done
    accSegFinal = accSeg;
    tstSegFinal = tstSeg;
    
end




% 
% 
% begIdx = find(ctrl == 0);
% endIdx = [(begIdx(2:end)-1); length(ctrl)];
% % nSamps = diff([begIdx endIdx], [], 2);
% 
% % enforce maximum samples for each segment
% % isToobig = nSamps > maxSamp;
% nSamps = diff([begIdx endIdx], [], 2);
% begIdxCorr = [];
% endIdxCorr = [];
% for i = 1:length(begIdx)
% 
%     if diff([begIdx(i) endIdx(i)], [], 2) > maxSamp % Too big! break up the segment into smaller ones
%         nRowsAdd = floor(nSamps(i)/maxSamp); 
%         xb = [1:nRowsAdd]';
%         
%         % begIdxCorr
%         begIdxSmall = begIdx(i) + xb*maxSamp + 1;
%         begIdxCorr = [begIdxCorr; begIdx(i); begIdxSmall];
%         
%         % endIdxCorr
%         endIdxSmall = begIdx(i) + xb*maxSamp;
%         endIdxCorr = [endIdxCorr; endIdxSmall; endIdx(i)];
%         
%     else
%         begIdxCorr = [begIdxCorr; begIdx(i)];
%         endIdxCorr = [endIdxCorr; endIdx(i)];
%         
%     end
%     
%     
%     
% end


% Gather data segments
% nSegs = length(begIdxCorr);
% for iSeg = 1:nSegs
%     accSeg{iSeg,1} = acc(begIdxCorr(iSeg):endIdxCorr(iSeg),:);
%     tstSeg{iSeg,1} = tst(begIdxCorr(iSeg):endIdxCorr(iSeg),:);
%     
% end


end

function [accProc, tstProc] = fillACC(acc, tst, ctrl, fs)
% pre-process acc data so that missing values are interpolated and
% inter-file spaces are NaNs spaced out according to common
% sampling-frequency of all files in session
% ctrl goes from 0 to N for a single file of N samples (some may be
% missing). For an NWB file where multiple files were concatenated, the 0
% to N ctrl count will reset and start again from 0 at the startint point
% of the next file. 


Ts = 1/fs;                           % Sampling Time
% tst = [0:10  14:20  25:30]*0.00274;       % Create Time Series With Gaps
% acc = rand(size(tst));                      % Create Matching Data
tst = tst';
tn = round(tst/Ts);                       % Create Indices With Gaps
dt = diff([0 tn]);                      % Create Vector Of Differences
tg = find(dt > 1);                      % Find Indices Of Gaps
gaps = dt(tg)-1;                        % Find Lengths Of Gaps
ti = linspace(min(tst),max(tst),max(tn));   % Create Continuous Time Vector
fi = interp1(tst,acc,ti);                   % Create Matching Data Vector
for k1 = 1:length(tg)                   % Loop Filling Gaps In ‘f’ With NaN
    q = [tg(k1):tg(k1)+gaps(k1)-1];
    fi(tg(k1):tg(k1)+gaps(k1)-2) = nan(1,gaps(k1)-1);
end


% First subdivide 




nCtrls = length(ctrl);
for ictrl = 1:nCtrls
    
    
end

% then interpolate any short missing values within recordings


end

function [Sacc, f, tSpec] = spectrogramacc3(acc, fs, cfg)

% Detrend data, linear best fit is subtracted from each channel
acc = detrend(acc);


% Highpass filter out slow components

[b,a] = butter(3, cfg.fcDetrend/(fs/2), 'high');
accFilt = filtfilt(b, a, acc);



%% Get combined triaxial spectrogram

window = floor(cfg.TWIN * fs);

% Sum PSDs from all 3 accel channels
clear Z S
for ch = 1:3
    [Z(:,:,ch), f, tSpec] = spectrogram(accFilt(:,ch), window, cfg.NOVERLAP, [], fs, 'yaxis');
    % tRef = linspace(tSpec(1), tSpec(end), numel(tSpec));
    S(:,:,ch) = abs(Z(:,:,ch));
    S(:,:,ch) = S(:,:,ch).^2;

end
% Combine spectral power from all three axes (summate)
Sacc = sum(S, 3);

end

function [ScleanCell, nRemovedBySegment, isMovArtCell] = removeMovArtInAll(SaccCell, cfg)
% First concatenate all segments spectrograms together and keep track of
% their place within segment cells
nSegs = length(SaccCell);
SaccAll = [];
origIdx = [];
for iSeg = 1:nSegs
    iSacc = SaccCell{iSeg,1};
    origIdx = [origIdx, 1:size(iSacc, 2)]; % keeps tabls of time windows in spectrograms
    SaccAll = [SaccAll, SaccCell{iSeg,1}];   
    
end


% Identify movement artifact windows in spectrogram

[~, isMovArt] = util.remoutliers(sum(SaccAll, 1), ...
    'bound', 'upper', ...
    'MADthresh', cfg.MADthresh);
temp = SaccAll;
temp(:,isMovArt) = NaN;
SaccMarkOutliers = SaccAll;
SaccMarkOutliers(:,isMovArt) = NaN;


% Show Spectrogram with detected movement artifacts marked as 100's values
if cfg.displayWorkflowFigs
    f4 = figure;
    ax4 = axes;
    ax4.Parent = f4;
    surf(tSpec, f, 10*log10(SaccMarkOutliers), ...
        'Parent', ax4, ...
        'EdgeColor', 'none');
    hold(ax4, 'on');
    xlabel('Time (min)');
    grid on
    axis(ax4, 'tight')
    view(0,90)
    colorbar
    % ax4.YLim = [0, 300];
    % ax4.CLim = [-80, -30];
    title('Mov Artifacts marked');
    ylabel('Frequency (Hz)');
    f4.Position = [2555 57 560 421];

end

% Show Spectrogram with movement artifacts removed totally
if cfg.displayWorkflowFigs
    f4 = figure;
    ax4 = axes;
    ax4.Parent = f4;
%     tset = t;
%     tset(isMovArt) = [];
    surf(1:size(temp, 2), f, 10*log10(temp), ...
        'Parent', ax4, ...
        'EdgeColor', 'none');
    hold(ax4, 'on');
    xlabel('samples');
    grid on
    axis(ax4, 'tight')
    view(0,90)
    colorbar
    ax4.YLim = [0, 150];
    % ax4.CLim = [-80, -30];
    title('Mov Artifacts removed')
    ylabel('Frequency (Hz)');
    f4.Position = [2554 566 560 420];

end


% Get average PSD free of movement artifact windows
ScleanAll = temp; % movement artifact windows removed
% PSD = mean(ScleanAll, 2);
if cfg.displayWorkflowFigs
    f1 = figure; ax = axes;
    plot(f, (PSD));
    grid on; 
    ax.XLim = [0, 35];
    %     ax.YLim = [0, popMaxPSD];
    xlabel('Frequency (Hz)');
%     title(['Minutes since harmaline inject: ' num2str(minutes(sessTabRow.harRefTime(1)))], 'Interpreter', 'none')

end


% Output nan-marked spectrograms back in their original cells
begIdx = find(origIdx == 1);
endIdx = [(begIdx(2:end)-1), size(ScleanAll, 2)];
for iSeg = 1:nSegs
    ScleanCell{iSeg,1} = ScleanAll(:,(begIdx(iSeg):endIdx(iSeg)));
    isMovArtCell{iSeg,1} = isMovArt(begIdx(iSeg):endIdx(iSeg));
    
end

% Remove nan-marked columns in each spectrogram (pertaining to time-window
% labeled as movemend artifact) for each segment
for iSeg = 1:nSegs
    iSaccnan = ScleanCell{iSeg,1};
    nanIdx = isnan(sum(iSaccnan, 1));
    iSaccClean = iSaccnan;
    iSaccClean(:,nanIdx) = [];
    
    ScleanCell{iSeg,1} = iSaccClean;
    nRemovedBySegment(iSeg,1) = sum(nanIdx);
    
end



end

