function [fitresult, gof] = createCurveFit(fClean, SClean)
%CREATEFIT(FCLEAN,SCLEAN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fClean
%      Y Output: SClean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Sep-2020 11:52:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fClean, SClean );

% Set up fittype and options.
ft = fittype( 'a*(1/((c*x + b).^n)) + d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.257471763753077 0.510706038304807 0.871838772907033 0.149294005559057 0.257508254123736];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'SClean vs. fClean', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel fClean
ylabel SClean
grid on


