function [fitresult, gof] = createFit_dose4expos2(tClean, bandPowDBgain)
%CREATEFIT(TCLEAN,BANDPOWDBGAIN)
%  Create a fit.
%
%  Data for 'capacitor fit' fit:
%      X Input : tClean
%      Y Output: bandPowDBgain
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Sep-2020 10:46:39


%% Fit: 'capacitor fit'.
[xData, yData] = prepareCurveData( tClean, bandPowDBgain );

% Set up fittype and options.
ft = fittype( 'v.*(1 - exp(-x./k))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.503840081846848 0.612809588835559];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'capacitor fit' );
h = plot( fitresult, xData, yData );
legend( h, 'bandPowDBgain vs. tClean', 'capacitor fit', 'Location', 'NorthEast' );
% Label axes
xlabel tClean
ylabel bandPowDBgain
grid on


