function dispSpecgram(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 26-Feb-2020 22:21:22

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'EdgeColor','none');

% Create ylabel
ylabel('Frequency (Hz)');

% Create xlabel
xlabel('Time (s)');

grid(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
% set(axes1,'CLim',[-170 -100]);
% Create colorbar
colorbar('peer',axes1);

